# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_data(object):
    def setupUi(self, data):
        data.setObjectName("data")
        data.resize(495, 140)
        self.verticalLayout = QtWidgets.QVBoxLayout(data)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cat = QtWidgets.QHBoxLayout()
        self.cat.setObjectName("cat")
        self.lbl_cat = QtWidgets.QLabel(data)
        self.lbl_cat.setObjectName("lbl_cat")
        self.cat.addWidget(self.lbl_cat)
        self.txt_cat_path = QtWidgets.QLineEdit(data)
        self.txt_cat_path.setReadOnly(True)
        self.txt_cat_path.setObjectName("txt_cat_path")
        self.cat.addWidget(self.txt_cat_path)
        self.btn_cat_load = QtWidgets.QPushButton(data)
        self.btn_cat_load.setObjectName("btn_cat_load")
        self.cat.addWidget(self.btn_cat_load)
        self.verticalLayout.addLayout(self.cat)
        self.dog = QtWidgets.QHBoxLayout()
        self.dog.setObjectName("dog")
        self.lbl_dog = QtWidgets.QLabel(data)
        self.lbl_dog.setObjectName("lbl_dog")
        self.dog.addWidget(self.lbl_dog)
        self.txt_dog_path = QtWidgets.QLineEdit(data)
        self.txt_dog_path.setReadOnly(True)
        self.txt_dog_path.setObjectName("txt_dog_path")
        self.dog.addWidget(self.txt_dog_path)
        self.btn_dog_load = QtWidgets.QPushButton(data)
        self.btn_dog_load.setObjectName("btn_dog_load")
        self.dog.addWidget(self.btn_dog_load)
        self.verticalLayout.addLayout(self.dog)
        self.buttons = QtWidgets.QDialogButtonBox(data)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setObjectName("buttons")
        self.verticalLayout.addWidget(self.buttons)

        self.retranslateUi(data)
        QtCore.QMetaObject.connectSlotsByName(data)

    def retranslateUi(self, data):
        _translate = QtCore.QCoreApplication.translate
        data.setWindowTitle(_translate("data", "加载数据集"))
        self.lbl_cat.setText(_translate("data", "猫："))
        self.btn_cat_load.setText(_translate("data", "加载数据集"))
        self.lbl_dog.setText(_translate("data", "狗："))
        self.btn_dog_load.setText(_translate("data", "加载数据集"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    data = QtWidgets.QDialog()
    ui = Ui_data()
    ui.setupUi(data)
    data.show()
    sys.exit(app.exec_())
